Final tweaks

diff --git a/centos_7_install b/centos_7_install
--- a/centos_7_install
+++ b/centos_7_install
@@ -181,7 +181,18 @@ _cmd_install_systemd() {
         return 13
     }
     echo "Etherus Daemon installed successfully"
-    echo "Use systemctl for administration: etherus.target"
+    systemctl start etherus.target && {
+        echo "Etherus Daemon started successfully"
+    } || {
+        echo "Failed to start Etherus Daemon" >&2
+    }
+    systemctl enable etherus.target && {
+        echo "Etherus Daemon enabled successfully"
+    } || {
+        echo "Failed to enable Etherus Daemon" >&2
+    }
+    echo "Use systemctl for administration"
+    echo "To check Etherus Daemon use: systemctl status etherus.target"
 }
 
 _cmd_firewall() {
diff --git a/centos_7_install_bootstrap b/centos_7_install_bootstrap
--- a/centos_7_install_bootstrap
+++ b/centos_7_install_bootstrap
@@ -15,21 +15,22 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #
-
-TMPFILE="$(mktemp /tmp/etherus-install.XXXXXX)" || {
-    echo "Failed to create script temp file" >&2
-    exit 1
-}
-trap "rm $TMPFILE" EXIT
-chmod 755 "$TMPFILE" || {
-    echo "Failed to change temp script file permissions: $TMPFILE" >&2
-    exit 2
-}
-curl -sL "https://raw.githubusercontent.com/ya-enot/etherctl/master/centos_7_install?$(date '+%Y-%m-%dT%H%M%S%z')" > "$TMPFILE" || {
-    echo "Failed to download install script" >&2
-    exit 3
-}
-"$TMPFILE" || {
-    echo "Failed to run Etherus install script: $TMPFILE" >&2
-    exit 4
-}
+(
+    TMPFILE="$(mktemp /tmp/etherus-install.XXXXXX)" || {
+        echo "Failed to create script temp file" >&2
+        exit 1
+    }
+    trap "rm $TMPFILE" EXIT
+    chmod 755 "$TMPFILE" || {
+        echo "Failed to change temp script file permissions: $TMPFILE" >&2
+        exit 2
+    }
+    curl -sL "https://raw.githubusercontent.com/ya-enot/etherctl/master/centos_7_install?$(date '+%Y-%m-%dT%H%M%S%z')" > "$TMPFILE" || {
+        echo "Failed to download install script" >&2
+        exit 3
+    }
+    "$TMPFILE" || {
+        echo "Failed to run Etherus install script: $TMPFILE" >&2
+        exit 4
+    }
+)
