Minor fixes

diff --git a/centos_7_install_bootstrap b/centos_7_install_bootstrap
--- a/centos_7_install_bootstrap
+++ b/centos_7_install_bootstrap
@@ -29,8 +29,20 @@
         echo "Failed to download install script" >&2
         exit 3
     }
-    sudo "$TMPFILE" || {
-        echo "Failed to run Etherus install script: $TMPFILE" >&2
-        exit 4
+    command -v sudo &>/dev/null && {
+        sudo "$TMPFILE" || {
+            echo "Failed to run Etherus install script: $TMPFILE" >&2
+            exit 4
+        }
+    } || {
+        [ "$(id -u)" != "0" ] && {
+            echo "You should act as superuser to install Etherus" >&2
+            exit 5
+        } || {
+            "$TMPFILE" || {
+                echo "Failed to run Etherus install script: $TMPFILE" >&2
+                exit 4
+            }
+        }
     }
 )
